# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.pull_request.base.ref }}-${{ runner.os }}-results
    - name: Build
      run: echo swift build -v
    - name: Run tests
      run: echo swift test -v
