# When a PR is squash-merged a new commit (with new sha) is created.
# The last successful run of the PR cached the number of warnings for each
# modules under the head commit's sha.
# This workflow reads the cache and stores it under the new commit's sha.

name: fix_cache_key_for_warning_counts

on:
  pull_request:
    types: [closed]

jobs:
  restore-and-store-cache:

    runs-on: ubuntu-latest

    steps:

    - name: restore cache with warning counts from head commit
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.pull_request.head.sha }}-warnings-cache

    - name: save cache with warning counts from merge commit
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.pull_request.merge_commit_sha }}-warnings-cache
