# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: merge_group.checks_requested

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
  merge_group:
    types: [checks_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: restore cache with warning counts from base commit
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.pull_request.base.sha }}-warnings-cache

    - name: compare
      run: |
        mkdir -pv warnings-cache
        echo `date +"%Y-%m-%dT%H:%M:%S%z"` ${{ github.event.pull_request.ref.sha }} | tee -a warnings-cache/build.txt
        cat warnings-cache/build.txt
        false # || true
