# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: merge_group.checks_requested

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review, closed]
  merge_group:
    types: [checks_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: sleep
      run: sleep 5

    - name: build
      run: |
        echo action ${{ github.event.action }}
        echo merge_commit_sha ${{ github.event.pull_request.merge_commit_sha }}
        echo head.sha ${{ github.event.pull_request.head.sha }}
        echo base.sha ${{ github.event.pull_request.base.sha }}
        echo head_commit.id ${{ github.event.merge_group.head_commit.id }}
        false || true

    - name: cache warnings count
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.base.ref }}-${{ runner.os }}-results
