# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: merge_group.checks_requested

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
  merge_group:
    types: [checks_requested]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: restore cache with warning counts from base commit
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.pull_request.base.sha }}-warnings-cache

    - name: build
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mkdir -pv warnings-cache
        echo `date +"%Y-%m-%dT%H:%M:%S%z"` ${{ github.event.pull_request.head.sha }} | tee -a warnings-cache/build.txt
        false || true
        gh api \
          --method PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/Aldrian-IT/warnings-caching/properties/values \
          -f "properties[][property_name]=environment" -f "properties[][value]=production" -f "properties[][property_name]=service" -f "properties[][value]=web" -f "properties[][property_name]=team" -f "properties[][value]=octocat"

    - name: save cache with warning counts from head commit
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.pull_request.head.sha }}-warnings-cache
