# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: merge_group.checks_requested_name

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
  merge_group:
    types: [checks_requested]

jobs:
  TMP:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare for tricking Danger
        run: |
          echo "The GITHUB_REPOSITORY is $GITHUB_REPOSITORY"
          echo "The GITHUB_EVENT_NAME is $GITHUB_EVENT_NAME"
          echo "The GITHUB_EVENT_PATH is $GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"
  TMP0:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare for tricking Danger
        env:
          GITHUB_EVENT_NAME: 'pull_request_fake'
        run: |
          echo "The GITHUB_REPOSITORY is $GITHUB_REPOSITORY"
          echo "The GITHUB_EVENT_NAME is $GITHUB_EVENT_NAME"
          echo "The GITHUB_EVENT_PATH is $GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: restore cache with warning counts from base commit
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.pull_request.base.sha }}-warnings-cache

    - name: compare
      run: |
        mkdir -pv warnings-cache
        echo `date +"%Y-%m-%dT%H:%M:%S%z"` ${{ github.event.pull_request.head.sha }} >> warnings-cache/build.txt
        cat warnings-cache/build.txt
        echo workflow ${{ github.workflow }}
        false || true

    - name: save cache with warning counts
      if: ${{ !cancelled() }}
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.head_commit.id }}-warnings-cache
