# This workflow runs all tests and caches the number of warnings.

name: push_main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: restore cache so that in case of a failure in a project/package the previous warning count isn't lost
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.before }}-warnings-cache

    - name: build
      run: |
        mkdir -pv warnings-cache
        echo `date +"%Y-%m-%dT%H:%M:%S%z"` ${{ github.event.head_commit.id }} | tee -a warnings-cache/build.txt
        false # || true

    - name: save cache with warning counts
      if: ${{ always() && github.event.action == 'push' }}
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.head_commit.id }}-warnings-cache
