# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.push.after }}-${{ runner.os }}-results
    - name: Build
      run: echo github.event.push.after: ${{ github.event.push.after }}
