# When a PR is squash-merged a new commit (with new sha) is created.
# The last successful run of the PR cached the number of warnings for each
# modules under the head commit's sha.
# This workflow reads the cache and stores it under the new commit's sha.

name: push_main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: restore cache so that in case of a failure the previous warning count isn't lost
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.before }}-warnings-cache

    - name: build
      run: |
        sleep 15
        mkdir -pv warnings-cache
        echo `date +"%Y-%m-%dT%H:%M:%S%z"` ${{ github.event.head_commit.id }} | tee -a warnings-cache/build.txt
        false # || true

    - name: save cache with warning counts
      if: always()
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.head_commit.id }}-warnings-cache
