# This workflow runs all tests and caches the number of warnings.

name: push_main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  TMP:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare for tricking Danger
        run: |
          echo "The GITHUB_REPOSITORY is $GITHUB_REPOSITORY"
          echo "The GITHUB_EVENT_NAME is $GITHUB_EVENT_NAME"
          echo "The GITHUB_EVENT_PATH is $GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"
  TMP0:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare for tricking Danger
        env:
          GITHUB_EVENT_NAME: 'pull_request'
        run: |
          echo "The GITHUB_REPOSITORY is $GITHUB_REPOSITORY"
          echo "The GITHUB_EVENT_NAME is $GITHUB_EVENT_NAME"
          echo "The GITHUB_EVENT_PATH is $GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"

  build:

    runs-on: ubuntu-latest

    steps:

    - name: restore cache so that in case of a failure in a project/package the previous warning count isn't lost
      uses: actions/cache/restore@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.before }}-warnings-cache

    - name: build
      run: |
        mkdir -pv warnings-cache
        echo `date +"%Y-%m-%dT%H:%M:%S%z"` ${{ github.event.head_commit.id }} | tee -a warnings-cache/build.txt
        false # || true

    - name: save cache with warning counts
      if: ${{ !cancelled() }}
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.head_commit.id }}-warnings-cache
