# When a PR is squash-merged a new commit (with new sha) is created.
# The last successful run of the PR cached the number of warnings for each
# modules under the head commit's sha.
# This workflow reads the cache and stores it under the new commit's sha.

name: push_main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: build
      run: |
        mkdir -pv warnings-cache
        echo `date +"%Y-%m-%dT%H:%M:%S%z"` ${{ github.event.pull_request.head.sha }} | tee -a warnings-cache/build.txt
        false || true

    - name: save cache with warning counts
      uses: actions/cache/save@v4.0.2
      with:
        path: warnings-cache
        key: ${{ github.event.push.after }}-warnings-cache
